language: node_js
node_js:
    - "0.10"
    - "stable"
env :
# Pour plus tard"
    - BROWSSER=chromium_browser

script: node_modules/karma/bin/karma start my.conf.js --single-run

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3 # give xvfb some time to start

before_script:
    - npm install
# cf:  http://javaetmoi.com/2014/02/developper-industrialiser-web-app-recherche-angularjs/                 	 	 
#  - npm install -g grunt-cli
after_success:
# cf:  http://javaetmoi.com/2014/02/developper-industrialiser-web-app-recherche-angularjs/    
# configurer https://coveralls.io/ ?             	 	 
  - grunt coverage
	
	
